### ISSUE TITLE
Great pooler, however one major drawback

### ISSUE THREAD

**Issue by daveywatt** [mdmnk/GameObjectPool#1]
Hey thanks for sharing your code, its a great pooling system.

One thing I noticed is that the prefab instances don't seem to be created on runtime, and only when my script calls PoolManager.Get()... or is the inspector lying to me?

Also, it would be great to see support for an array/list of prefabs per pool that can then be returned at random, as it's common to require a random prefab (such as effect) when an event occurs.

Nice work!

**Comment by mdmnk** [comment]
Hey @daveywatt thanks for the feedback. It happened to escape my notice until today. 

> One thing I noticed is that the prefab instances don't seem to be created on runtime, and only when my script calls PoolManager.Get()... or is the inspector lying to me?

I'm not sure what the state of the code was when you posted this, but I made some improvements today that should address any previous issues regarding instantiation. Currently the pool will instantiate the number of objects set in the **Starting Item Count** field.

If you leave the **Allow Unrestricted Growth** option checked objects will continue to be instantiated when `PoolManager.Get()` is requested and the pool is empty.

> Also, it would be great to see support for an array/list of prefabs per pool that can then be returned at random, as it's common to require a random prefab (such as effect) when an event occurs.

That would be a pretty simple feature to add, I'll look into adding a `RandomPool` which extends `List` and shuffles the elements. In the meantime you could use several small pools and randomly choose which to pull from, or attach a script to the prefab which randomizes its behavior at runtime.

**Comment by w4ffl35** [comment]
After several years I am revisiting this repository: 

Indeed prefabs are created at runtime. I am assigning this to myself and will fix.

**Comment by w4ffl35** [comment]
As of v1.1.0 prefabs can now be generated in the editor by clicking the "regenerate pool" button on the game object containing the Pool Manager class.

I'm splitting the second half of this into another ticket
